<?xml version="1.0"?>
<package format="3">
  <name>dron_bringup_pkg</name>
  <version>0.2.0</version>
  <description>Modo manual ROS 2 + PX4 en C++ para dron con Pixhawk: teclado, Offboard velocity setpoints, telemetria y seguridad.</description>
  <maintainer email="alexalvila@gmail.com">alex</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>px4_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz2</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>